# Generated by Django 4.1.2 on 2022-11-24 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docktrialcomments",
            name="editor_profile_sign",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
