# Generated by Django 4.1.2 on 2022-11-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0003_alter_docktrialcomments_editor_profile_sign"),
    ]

    operations = [
        migrations.AddField(
            model_name="docktrial",
            name="specification",
            field=models.TextField(null=True),
        ),
    ]
