# Generated by Django 4.1.2 on 2022-12-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0004_docktrial_specification"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="docktrial",
            table="trials",
        ),
    ]
