# Generated by Django 4.1.2 on 2022-12-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trials", "0010_alter_docktrial_trial_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="docktrialcomments",
            name="department",
            field=models.CharField(
                choices=[
                    ("Hull Production Department", "HPD"),
                    ("Piping Department", "PID"),
                    ("Outfitting Department", "OD"),
                    ("Electric Deepartment", "ED"),
                    ("Commissioning Department", "CD"),
                    ("Quality Control Department", "QCD"),
                    ("Purchasing and Logistics Deparment", "P&L"),
                    ("Painting Department", "PD"),
                    ("Design Office", "DO"),
                    ("Service", "S"),
                    ("Construction Office", "CO"),
                ],
                default="Construction Office",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="docktrialcomments",
            name="status",
            field=models.CharField(
                choices=[("Open", "Open"), ("Close", "Close")],
                default="Open",
                max_length=100,
            ),
        ),
    ]
