# Generated by Django 4.1.2 on 2022-11-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_profile_side"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="side",
            field=models.IntegerField(
                blank=True, choices=[(0, "Shipowner"), (1, "Contractor")], default=1
            ),
        ),
    ]
