# Generated by Django 4.1.2 on 2022-11-24 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_profile_user_alter_profile_your_sign"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="your_sign",
        ),
    ]
