# Generated by Django 4.1.2 on 2022-12-07 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_profile_your_sign"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="side",
        ),
    ]
