# Generated by Django 4.1.2 on 2022-12-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_profile_side"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="contact_number",
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name="profile",
            name="department",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
