# Generated by Django 4.1.2 on 2022-12-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_profile_contact_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={
                "permissions": (
                    ("designer_field_edit", "Can edit designer comment fields"),
                    ("contractor_field_edit", "Can edit contractor comment fields"),
                    ("shipowner_field_edit", "Can edit shipowner comment fields"),
                )
            },
        ),
    ]
