# Generated by Django 4.1.2 on 2022-12-16 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_profile_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={},
        ),
    ]
